name: Run all D Tests
on: [push, pull_request]

jobs:
  test:
    name: Dub Tests
  
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-latest
        
    - name: Run tests
      run: dub test
